{% set name = "perl-text-roman" %}
{% set version = "3.5" %}
{% set sha256 = "cb4a08a3b151802ffb2fce3258a416542ab81db0f739ee474a9583ffb73e046a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/S/SY/SYP/Text-Roman-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  script:
    - perl Makefile.PL INSTALLDIRS=site
    - make
    - make test
    - make install

requirements:
  build:
    - make
    - perl >=5.22
  run:
    - perl >=5.22

test:
  imports:
    - Text::Roman

about:
  home: https://metacpan.org/pod/Text::Roman
  summary: 'Allows conversion between Roman and Arabic algarisms'
  license: Artistic-1.0-Perl

extra:
  recipe-maintainers:
    - Pombert-JF
